### ISSUE TITLE
Can you help me with adding p-value labels?

### ISSUE THREAD

**Issue by ling9802** [r-link/corrmorant#28]
As you can see, the magnitude of the correlation coefficient does not completely determine the significance of the relationship between two variables. Sometimes it is necessary to indicate whether there is a significant correlation between two variables by adding p-value labels (such as asterisks). Could you please help me with this? Thank you very much for your assistance. 

The first image is the plot generated by my code, and the second image shows where and what type of labels I would like to add.

<img width="776" alt="image" src="https://user-images.githubusercontent.com/72969353/223986648-ae7bd9da-98a0-42a3-8caa-dd09538228fd.png">

**Comment by ling9802** [comment]
This is my code for first figure.



ggcorrm(data,mapping = aes(col = .corr, fill = .corr),bg_dia = "white",  
        rescale = "by_sd") +
  lotri(geom_smooth(method = "loess", size =1,se = F)) + 
  lotri(geom_point(alpha = 0.5,color="black", size = 1)) + 
  utri_heatcircle(col="white",color="black") + 
  utri_corrtext(size = 3,color="black",pch=21) + 
  dia_names(y_pos = 0.4,size =2.5,angle=-45, color = "black")+ 
  scale_color_gradientn(colours = (RColorBrewer::brewer.pal(8,"RdBu")))+
  scale_fill_gradientn(colours = (RColorBrewer::brewer.pal(8,"RdBu")))+
  theme(legend.background = element_blank(),
        legend.title = element_blank())+
  guides(color=guide_colorbar(direction="vertical",reverse=F,barwidth=unit(.5,"cm"),
                              barheight=unit(15,"cm")))+
  coord_cartesian(clip='off')

**Comment by r-link** [comment]
Hi there,
you might have noticed that I made it intentionally hard to add p-value labels. The reason is that most cases, p-values for everything in a correlation matrix do not make much sense (most of the tests you are doing are probably scientifically  not meaningful to you) and without a correction for multiple comparisons, they are essentially worthless because they will not fulfill the error rate guarantees they are defined for.

Anyway, it is of course possible - you can use `utri_funtext()` to get a text label into the upper triangle that is defined by a user-speficied function. Here's a hacky way to do  this with adjusted p-values. Just tried it briefly, but it seems to work:

```
# define function for corrected and formatted p values
adjust_cor <- function(x, y, n_var, method = "holm"){
  # get raw p value  
  p   <- cor.test(x, y)$p.value
  # adjust for multiple comparicons
  p.adj <- p.adjust(p = p, method = method, 
                    n = n_var * (n_var - 1) / 2) # number of combinations of n_var variables
  # prepare for plotting
  paste0(format(round(cor(x, y), 2), nsmall = 2), gtools::stars.pval(p.adj))
}

# try out (the number of corrections must be based on the number of numeric variables, so 13 in your case)
ggcorrm(drosera) +
  utri_funtext(~adjust_cor(.x, .y, n_var = sum(sapply(drosera, is.numeric))))
```

I could of course make a built-in function for things like this, but as mentioned above there's a reason it is complicated: I want to avoid that people do this, unless they really know what they are doing. The package is a tool for data visualization and screening, not for statistical inference.

**Comment by ling9802** [comment]
Thank you so much for your help in resolving my code issues. I truly appreciate your expertise and willingness to assist me. Your support has been invaluable, and I am grateful for the time and effort you have dedicated to helping me. Thank you again for everything.

"However, I still have a question. How can I remove the labels on the right and top of the heatmap? I think the diagonal labels already provide sufficient information."

**Comment by r-link** [comment]
Hi there. I guess you refer to the facet labels, which in ggplot are controlled by the `strip.text` theme element.
You can remove them this way:

```
 corrmorant(drosera) + theme(strip.text = element_blank())
 ```

**Comment by ling9802** [comment]
I would like to express my heartfelt gratitude for your exceptional work.
